/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package entorno;

/**
 *
 * @author orarroyo
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        num1 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Suma (+)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 190, 90, 22);

        jButton2.setText("Resta (-)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 230, 90, 22);

        jButton3.setText("Multiplicación (x)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 190, 130, 22);

        jButton4.setText("División ( / )");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(260, 230, 130, 22);

        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        getContentPane().add(num1);
        num1.setBounds(100, 40, 64, 22);
        getContentPane().add(num2);
        num2.setBounds(100, 80, 64, 22);

        jLabel1.setText("NÚMERO 1:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 70, 16);

        jLabel2.setText("NÚMERO 2:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 70, 16);

        resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(resultado);
        resultado.setBounds(243, 50, 150, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CALCULADORA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 10, 120, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int start = 32, end = 126;
        char[] ascii = new char[end - start - 9];
        for (int i = start; i < ascii.length; i++) {
            if ((i < 48 || i > 57) && i != 43 && i != 45) {
                ascii[i] = (char) i;
            }
        }
        int sw = 0;
        for (char l : ascii) {
            String a = String.valueOf(l);
            if (num1.getText().contains(a)) {
                sw = 1;
                System.out.println("hola");
            }
            if (num2.getText().contains(a)) {
                sw = 1;
                System.out.println("hola");
            }
        }
        if (sw == 1) {
            resultado.setText("Error mamahuevo 2");
        } else {
            double x = Double.parseDouble(num1.getText()) - Double.parseDouble(num2.getText());
            resultado.setText("" + x);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int start = 32, end = 126;
        char[] ascii = new char[end - start - 9];
        for (int i = start; i < ascii.length; i++) {
            if ((i < 48 || i > 57) && i != 43 && i != 45) {
                ascii[i] = (char) i;
            }
        }
        int sw = 0, div = 0;
        for (char l : ascii) {
            String a = String.valueOf(l);
            if (num1.getText().contains(a)) {
                sw = 1;
                System.out.println("hola");
            }
            if (num2.getText().contains(a)) {
                div = 1;
                System.out.println("hola");
            }
        }
        if (sw == 1) {
            resultado.setText("Error mamahuevo");
        } else if (div != 1) {
            if (Double.parseDouble(num2.getText()) != 0) {
                double x = Double.parseDouble(num1.getText()) / Double.parseDouble(num2.getText());
                resultado.setText("" + x);
            } else {
                resultado.setText("División por cero.");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int start = 32, end = 126;
        char[] ascii = new char[end - start - 9];
        for (int i = start; i < ascii.length; i++) {
            if ((i < 48 || i > 57) && i != 43 && i != 45) {
                ascii[i] = (char) i;
            }
        }
        int sw = 0;
        for (char l : ascii) {
            String a = String.valueOf(l);
            if (num1.getText().contains(a)) {
                sw = 1;
                System.out.println("hola");
            }
            if (num2.getText().contains(a)) {
                sw = 1;
                System.out.println("hola");
            }
        }
        if (sw == 1) {
            resultado.setText("Error mamahuevo");
        } else {
            double x = Double.parseDouble(num1.getText()) + Double.parseDouble(num2.getText());
            resultado.setText("" + x);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int start = 32, end = 126;
        char[] ascii = new char[end - start - 9];
        for (int i = start; i < ascii.length; i++) {
            if ((i < 48 || i > 57) && i != 43 && i != 45) {
                ascii[i] = (char) i;
            }
        }
        int sw = 0;
        for (char l : ascii) {
            String a = String.valueOf(l);
            if (num1.getText().contains(a)) {
                sw = 1;
                System.out.println("hola");
            }
            if (num2.getText().contains(a)) {
                sw = 1;
                System.out.println("hola");
            }
        }
        if (sw == 1) {
            resultado.setText("Error mamahuevo");
        } else {
            double x = Double.parseDouble(num1.getText()) * Double.parseDouble(num2.getText());
            resultado.setText("" + x);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
